import React,{useEffect,useState} from 'react';
import {Check,RefreshCw,Sparkles} from 'lucide-react';
import {AVATAR_TYPES,generateAvatar,normalizeAvatar} from './avatar.js';
import {AvatarView} from './AvatarView.jsx';

export function AvatarSettings({avatar,interest,onSave}){
 const [draft,setDraft]=useState(()=>normalizeAvatar(avatar)),[busy,setBusy]=useState(false),[message,setMessage]=useState('');useEffect(()=>setDraft(normalizeAvatar(avatar)),[avatar]);
 const generate=async()=>{setBusy(true);setMessage('Der persönliche Lernbegleiter wird gestaltet …');const result=await generateAvatar(interest,draft.type);setDraft(result);setMessage(result.notice||'Vorschlag fertig. Bitte prüfen und anschließend freigeben.');setBusy(false)};
 const approve=async()=>{const approved={...draft,approved:true};setDraft(approved);await onSave(approved);setMessage('Avatar freigegeben und gespeichert. Er begleitet dein Kind jetzt beim Lernen. ✓')};
 return <section className="avatar-settings"><div className="avatar-settings-head"><AvatarView avatar={draft}/><div><h2>Persönlicher Lernavatar</h2><p>Du bestimmst den Stil. Die KI erstellt nur einen Vorschlag, den du als Elternteil freigibst.</p><div className="avatar-traits"><span>👕 {draft.outfit}</span><span>⚡ {draft.ability}</span><strong>{draft.approved?'✓ Von den Eltern freigegeben':'Noch nicht freigegeben'}</strong></div></div></div><div className="avatar-controls"><label>Figur<select value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value,approved:false})}>{AVATAR_TYPES.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Name<input value={draft.name} maxLength="24" onChange={event=>setDraft({...draft,name:event.target.value,approved:false})}/></label><label>Farbe<select value={draft.color} onChange={event=>setDraft({...draft,color:event.target.value,approved:false})}>{['violet','blue','green','orange','pink'].map(color=><option key={color}>{color}</option>)}</select></label></div><div className="avatar-buttons"><button type="button" disabled={busy} onClick={generate}><Sparkles/> {busy?'KI gestaltet …':'Mit KI gestalten'}</button><button type="button" disabled={busy||!draft.name.trim()} onClick={approve}><Check/> Prüfen & freigeben</button><button type="button" onClick={()=>setDraft(normalizeAvatar(avatar))}><RefreshCw/> Zurücksetzen</button></div>{message&&<p role="status">{message}</p>}</section>;
}
