import React,{useState} from 'react';
import {Check} from 'lucide-react';

export function DailySettings({settings,onSave}){
 const [draft,setDraft]=useState(settings),[saved,setSaved]=useState(false);
 const update=(key,value)=>{setSaved(false);setDraft(current=>({...current,[key]:value}))};
 const save=async()=>{await onSave({...draft,dailyGoal:Math.max(5,Math.min(30,Number(draft.dailyGoal)||15)),maxMinutes:Math.max(0,Math.min(30,Number(draft.maxMinutes)||0))});setSaved(true)};
 return <section className="daily-settings"><h2>Persönlicher Tagesplan</h2><p>Die App mischt fällige, neue und schwierige Wörter automatisch.</p><div><label>Tägliches Ziel<select value={draft.dailyGoal} onChange={event=>update('dailyGoal',event.target.value)}>{[10,15,20,25,30].map(value=><option key={value} value={value}>{value} Wörter</option>)}</select></label><label>Maximale Lernzeit<select value={draft.maxMinutes} onChange={event=>update('maxMinutes',event.target.value)}>{[0,5,10,15].map(value=><option key={value} value={value}>{value?`${value} Minuten`:'Ohne Zeitlimit'}</option>)}</select></label><label>Meistertest nach<select value={draft.masteryDelayDays} onChange={event=>update('masteryDelayDays',Number(event.target.value))}><option value="3">3 Tagen</option><option value="7">7 Tagen</option></select></label><label>Anteil neuer Wörter<input type="range" min="0" max="100" step="10" value={draft.newShare} onChange={event=>update('newShare',Number(event.target.value))}/><b>{draft.newShare}% neu</b></label><label className="weekend-setting"><input type="checkbox" checked={draft.weekends} onChange={event=>update('weekends',event.target.checked)}/><span>Auch am Wochenende anbieten</span></label><label className="weekend-setting"><input type="checkbox" checked={draft.streakProtection} onChange={event=>update('streakProtection',event.target.checked)}/><span>Ein Streak-Schutz pro Serie</span></label></div><button onClick={save}><Check/> {saved?'Gespeichert':'Lernplan speichern'}</button></section>;
}
