import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, BookOpen, Check, ChevronRight, Flame, Gift, Lock, Settings, Sparkles, Star, Trophy, Volume2, X} from 'lucide-react';
import './styles.css';
import {exportBackup, getAll, importBackup, put, replaceAll, saveAttempt, seedDatabase} from './storage';
import {normalizeVocabularyPair} from './ocr';
import {OcrWorkspace} from './ocrWorkspace';
import {cloudConfigured, downloadCloudBackup, getCloudStatus, getCloudUser, markCloudPending, signIn, signOut, subscribeCloudStatus, syncCloudData, uploadCloudBackup} from './cloud';
import {calculateAchievementProgress, nextRewardProgress, nextStreak, scoreStage, sortUnitsForDailyLearning, summarizeLearning, syncRewards, unitDayLabel, withMissingDates} from './learning';
import {buildParentAnalytics} from './learning';
import {ParentInsights,UnitAdmin} from './parentTools';
import {StageResult} from './stageResult';

const initialUnits=[
 {id:'animals',name:'Animals & Pets',icon:'🐶',accent:'#7248e8',soft:'#f2edff',done:4,words:12,stars:[3,3,2,1,0,0,0],pairs:[['Hund','dog'],['Katze','cat'],['Vogel','bird'],['Pferd','horse'],['Maus','mouse']]},
 {id:'school',name:'At School',icon:'🎒',accent:'#2f8cfa',soft:'#eaf4ff',done:2,words:15,stars:[3,2,0,0,0,0,0],pairs:[['Buch','book'],['Stift','pencil'],['Tisch','desk'],['Schule','school'],['Lehrer','teacher']]},
 {id:'food',name:'Food & Drinks',icon:'🍎',accent:'#ee6d44',soft:'#fff0ea',done:0,words:10,stars:[0,0,0,0,0,0,0],pairs:[['Apfel','apple'],['Brot','bread'],['Wasser','water'],['Milch','milk'],['Käse','cheese']]}
];
const levels=[['👀','Wort erkennen','Wähle die richtige Übersetzung aus','#38c976'],['🧩','Buchstaben-Puzzle','Sortiere die gemischten Buchstaben','#4788f7'],['🧱','Wortbausteine','Setze das Wort aus Teilen zusammen','#f29a38'],['🔤','Lückenwort','Ergänze die fehlenden Buchstaben','#ed6548'],['💡','Anfangshilfe','Schreibe das Wort mit kleiner Hilfe','#df5a9e'],['🧠','Merken & schreiben','Merke dir das Wort und schreibe es','#8b67e8'],['✏️','Freies Schreiben','Schreibe die Übersetzung ohne Hilfe','#6742ce']];
const rewards=[['🎮','30 Min. extra Spielzeit',50,true],['🍦','Ein Eis aussuchen',100,false],['🎬','Filmabend bestimmen',150,false]];
const achievementCatalog=[
 {id:'first-word',icon:'🌱',title:'Der erste Schritt',description:'Lerne dein erstes Wort richtig.',metric:'learned',target:1},
 {id:'ten-words',icon:'🚀',title:'Wörter-Rakete',description:'Lerne 10 Wörter richtig.',metric:'learned',target:10},
 {id:'fifty-words',icon:'🏆',title:'VokabelHero',description:'Lerne 50 Wörter richtig.',metric:'learned',target:50},
 {id:'first-try-10',icon:'🎯',title:'Volltreffer',description:'Schaffe 10 Wörter beim ersten Versuch.',metric:'firstTry',target:10},
 {id:'three-units',icon:'📚',title:'Bücherwurm',description:'Übe in 3 verschiedenen Units.',metric:'units',target:3},
 {id:'star-collector',icon:'⭐',title:'Sternesammler',description:'Sammle insgesamt 15 Sterne.',metric:'stars',target:15},
 {id:'three-days',icon:'🔥',title:'Dranbleiber',description:'Lerne an 3 verschiedenen Tagen.',metric:'days',target:3},
 {id:'hundred-tries',icon:'🧠',title:'Trainings-Profi',description:'Bearbeite insgesamt 100 Aufgaben.',metric:'attempts',target:100}
];

function Stars({n=0}){return <span className="stars">{[0,1,2].map(i=><Star key={i} size={16} fill={i<n?'#ffbd2e':'#ddd8e6'} color={i<n?'#ffbd2e':'#ddd8e6'}/>)}</span>}
function SyncIndicator({status,user}){if(!user)return null;const icons={synced:'✓',syncing:'↻',offline:'⌁',pending:'•',error:'!'};return <div className={`sync-indicator ${status.state}`} role="status" aria-live="polite"><b>{icons[status.state]||'☁'}</b><span>{status.message}</span></div>}
function Header({back,onBack,parent,onParent}){return <header><div className="head-inner">{back?<button className="icon-btn" onClick={onBack}><ArrowLeft/></button>:<div className="brand"><span>V</span>VokabelHero</div>}<div className="head-actions"><button className="sound"><Volume2 size={19}/></button>{!back&&<button className="parent" onClick={onParent}><Settings size={17}/> Eltern</button>}{back&&<div className="brand mini"><span>V</span></div>}</div></div></header>}
function Home({onUnit,onRewards,onAchievements,onParent,units=initialUnits,stats,rewardProgress}){const activeUnits=units.filter(unit=>!unit.archived&&!unit.deletedAt);const sorted=sortUnitsForDailyLearning(activeUnits);const newest=sorted[0];return <><Header onParent={onParent}/><main className="home"><section className="hello"><div><div className="eyebrow">GUTEN TAG, EMMA! 👋</div><h1>Heute Neues lernen,<br/><em>Altes richtig festigen.</em></h1><p>Jede neue Vokabelliste ist eine eigene Unit und bleibt zum Wiederholen erhalten.</p></div><div className="mascot"><span className="burst">✨</span><div className="owl">🦉</div><b>Los geht's!</b></div></section>{newest&&<button className="today-card" onClick={()=>onUnit(newest)}><span>☀️</span><div><small>DEINE UNIT FÜR HEUTE</small><b>{newest.name}</b><p>{newest.words} neue Wörter warten auf dich</p></div><ChevronRight/></button>}<section className="progress-card"><div className="progress-icon">🏆</div><div className="progress-main"><div className="progress-title"><b>Nächste Belohnung</b><strong>{stats.learnedWords} <small>/ {rewardProgress.next?.milestone||stats.learnedWords} Wörter</small></strong></div><div className="bar"><i style={{width:`${rewardProgress.percent}%`}}/></div><p>{rewardProgress.next?<>Noch <b>{rewardProgress.remaining} richtige Wörter</b> bis „{rewardProgress.next.title}“ {rewardProgress.next.emoji}</>:<b>Alle Belohnungen freigeschaltet! 🎉</b>}</p></div><button onClick={onRewards}>Vitrine <ChevronRight size={18}/></button></section><div className="section-title"><div><h2>Üben & wiederholen</h2><p>Ältere Units verschwinden nie – so kannst du sie jeden Tag festigen.</p></div><div className="total"><BookOpen size={20}/> <b>{activeUnits.reduce((sum,u)=>sum+u.words,0)}</b><span>Wörter insgesamt</span></div></div><section className="unit-grid">{sorted.map((u,i)=><button className="unit-card" key={u.id} onClick={()=>onUnit(u)} style={{'--accent':u.accent,'--soft':u.soft}}><div className="unit-top"><div className="unit-icon">{u.icon}</div><span>{unitDayLabel(u)}</span></div><h3>{u.name}</h3><p>{u.words} Vokabeln {u.lastPracticedAt?'· zuletzt geübt':'· bereit zum Lernen'}</p><div className="mini-levels">{u.stars.map((s,j)=><div className={(j>u.done?'locked ':'')+'mini-step'} key={j}>{j>u.done?<Lock size={12}/>:j+1}<Stars n={s}/></div>)}</div><div className="unit-foot"><span>{u.done===0?'Noch nicht gestartet':`${u.done} von 7 Stufen geschafft`}</span><div><i style={{width:`${Math.round(u.done/7*100)}%`}}/></div><ChevronRight/></div></button>)}</section></main><Bottom active="home" onRewards={onRewards} onAchievements={onAchievements}/></>}
function Bottom({active,onHome,onRewards,onAchievements}){return <nav className="bottom"><button className={active==='home'?'active':''} onClick={onHome}><BookOpen/>Lernen</button><button className={active==='rewards'?'active':''} onClick={onRewards}><Trophy/>Vitrine</button><button className={active==='achievements'?'active':''} onClick={onAchievements}><Star/>Erfolge</button></nav>}
function Unit({unit,onBack,onPlay}){const stars=[...(unit.stars||[]),0,0].slice(0,7);return <><Header back onBack={onBack}/><main className="unit-page"><div className="unit-heading"><div className="big-icon">{unit.icon}</div><div><div className="eyebrow">DEINE UNIT</div><h1>{unit.name}</h1><p>{unit.words} Vokabeln · <b>{unit.done} von 7 Stufen geschafft</b></p></div></div><div className="path">{levels.map((l,i)=>{const unlocked=i<=unit.done;return <React.Fragment key={l[1]}><button className={'level '+(!unlocked?'islocked':'')} onClick={()=>unlocked&&onPlay(i)} style={{'--level':l[3]}}><div className="level-num">{unlocked?l[0]:<Lock/>}</div><div className="level-copy"><small>STUFE {i+1}</small><h3>{l[1]}</h3><p>{unlocked?l[2]:'Schaffe zuerst die vorherige Stufe'}</p></div>{unlocked&&<Stars n={stars[i]}/>} {unlocked&&<ChevronRight/>}</button>{i<6&&<div className={'connector '+(i<unit.done?'done':'')}/>}</React.Fragment>})}</div><button className="words"><BookOpen/> <span><b>Vokabeln dieser Unit ansehen</b><small>Alle {unit.words} Wörter anzeigen</small></span><ChevronRight/></button></main></>}

const shuffled=value=>[...value].sort(()=>Math.random()-.5);
function Game({unit,level,onBack,onFinish,onAttempt}){
 const [wordIndex,setWordIndex]=useState(0),[picked,setPicked]=useState([]),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[solved,setSolved]=useState(false),[visible,setVisible]=useState(level===5),[hadMistake,setHadMistake]=useState(false),[results,setResults]=useState([]),[sessionId]=useState(()=>crypto.randomUUID()),[answerStartedAt,setAnswerStartedAt]=useState(()=>Date.now()),[lastSave,setLastSave]=useState(null),[streak,setStreak]=useState(0),[maxStreak,setMaxStreak]=useState(0);
 const pair=unit.pairs[wordIndex],word=pair[1].trim().toLowerCase();
 const letters=useMemo(()=>shuffled(word.split('')),[word]);
 const chunkSize=Math.max(1,Math.ceil(word.length/Math.min(3,word.length)));
 const chunks=useMemo(()=>shuffled(word.match(new RegExp(`.{1,${chunkSize}}`,'g'))||[word]),[word]);
 const choices=useMemo(()=>shuffled([word,...shuffled(unit.pairs.filter((_,i)=>i!==wordIndex).map(p=>p[1].trim().toLowerCase())).slice(0,2)]),[unit.id,wordIndex,word]);
 useEffect(()=>{setVisible(level===5);if(level===5){const timer=setTimeout(()=>setVisible(false),2500);return()=>clearTimeout(timer)}},[level,wordIndex]);
 const record=(correct,response)=>{const answeredAt=Date.now();const pending=onAttempt({unitId:unit.id,level:level+1,word,correct,firstTry:correct&&!hadMistake,response,sessionId,durationMs:Math.max(0,answeredAt-answerStartedAt)});setAnswerStartedAt(answeredAt);return pending};
 const success=response=>{const currentStreak=nextStreak(streak,true);setStreak(currentStreak);setMaxStreak(current=>Math.max(current,currentStreak));setLastSave(record(true,response));setSolved(true);setFeedback(currentStreak>=3?`Wow! ${currentStreak} richtige Antworten in Folge 🔥`:'Super! Genau richtig 🎉')};
 const fail=(message,response)=>{record(false,response);setStreak(nextStreak(streak,false));setHadMistake(true);setFeedback(message)};
 const check=value=>value.trim().toLowerCase()===word?success(value):fail('Fast! Schau noch einmal genau hin 💡',value);
 const choosePart=(part,index)=>{if(picked.some(x=>x.index===index))return;const current=picked.map(x=>x.value).join('');if(word.startsWith(current+part)){const next=[...picked,{value:part,index}];setPicked(next);setFeedback('Klasse! Weiter so ✨');if(next.map(x=>x.value).join('')===word)success(next.map(x=>x.value).join(''))}else fail('Fast! Versuch einen anderen Baustein 💡',current+part)};
 const advance=async()=>{if(lastSave)await lastSave;const nextResults=[...results,{word,firstTry:!hadMistake}];if(wordIndex===unit.pairs.length-1){onFinish(nextResults,{maxStreak});return}setResults(nextResults);setWordIndex(index=>index+1);setPicked([]);setAnswer('');setFeedback('');setSolved(false);setHadMistake(false);setLastSave(null);setAnswerStartedAt(Date.now())};
 let exercise;
 if(level===0)exercise=<div className="choice-grid">{choices.map(choice=><button disabled={solved} key={choice} onClick={()=>check(choice)}>{choice}</button>)}</div>;
 else if(level===1)exercise=<><div className="answer">{word.split('').map((_,i)=><span className={picked[i]?'filled':''} key={i}>{picked[i]?.value}</span>)}</div><div className="letters">{letters.map((letter,i)=><button disabled={picked.some(x=>x.index===i)} onClick={()=>choosePart(letter,i)} key={i}>{letter}</button>)}</div></>;
 else if(level===2)exercise=<><div className="chunk-answer">{picked.map(x=><span key={x.index}>{x.value}</span>)}</div><div className="chunk-grid">{chunks.map((chunk,i)=><button disabled={picked.some(x=>x.index===i)} onClick={()=>choosePart(chunk,i)} key={i}>{chunk}</button>)}</div></>;
 else {const clue=level===3?word.split('').map((c,i)=>i%2===0?c:'_').join(' '):level===4?`${word.slice(0,Math.min(2,word.length))}${'_'.repeat(Math.max(0,word.length-2))}`:level===5&&visible?word:null;exercise=<div className="write-exercise">{clue&&<div className={'word-clue '+(level===5?'memory-word':'')}>{clue}</div>}{level===5&&!visible&&!solved&&<p className="memory-gone">Jetzt aus dem Gedächtnis schreiben!</p>}<input key={`${level}-${wordIndex}`} autoFocus value={answer} disabled={solved||(level===5&&visible)} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&answer.trim()&&check(answer)} placeholder="Englisches Wort eingeben"/><button onClick={()=>check(answer)} disabled={solved||(level===5&&visible)||!answer.trim()}>Prüfen</button></div>}
 return <div className="game" style={{'--level':levels[level][3]}}><div className="game-head"><button className="icon-btn" onClick={onBack}><X/></button><div className="game-progress"><span>WORT {wordIndex+1} VON {unit.pairs.length}</span><div><i style={{width:`${(wordIndex+1)/unit.pairs.length*100}%`}}/></div></div><div className="streak"><Flame fill="#ff9e33" color="#ff9e33"/> {streak}</div></div><main className="game-main"><div className="game-label">{levels[level][0]} STUFE {level+1} · {levels[level][1].toUpperCase()}</div><h1>Wie heißt <em>„{pair[0]}“</em> auf Englisch?</h1><p className="hint">{levels[level][2]}</p>{exercise}<div className={'feedback '+(solved?'good':'')}>{feedback||'💡 Nimm dir Zeit – du schaffst das!'}</div>{solved&&<button className="primary" onClick={advance}>{wordIndex===unit.pairs.length-1?'Stufe abschließen':'Nächstes Wort'} <ChevronRight/></button>}</main></div>
}
function Rewards({onBack,onHome,onAchievements,rewardItems=[],stats,rewardProgress}){return <><Header back onBack={onBack}/><main className="rewards"><div className="trophy-hero"><span>🏆</span><div><div className="eyebrow">DEINE SAMMLUNG</div><h1>Trophäen-Vitrine</h1><p>Jedes gelernte Wort bringt dich deinem nächsten Wunsch näher!</p></div></div><div className="reward-progress"><div><Sparkles/><b>{stats.learnedWords} Wörter gelernt</b><span>{rewardProgress.next?`Noch ${rewardProgress.remaining} bis ${rewardProgress.next.title}`:`Alle ${rewardItems.length} Belohnungen freigeschaltet!`}</span></div><div className="bar"><i style={{width:`${rewardProgress.percent}%`}}/></div></div><h2>Deine Belohnungen</h2><div className="reward-grid">{rewardItems.map(r=><div className={'reward '+(!r.unlocked?'future':'')} key={r.id}>{r.unlocked?<div className="ribbon">GESCHAFFT!</div>:<Lock className="reward-lock"/>}<div className="reward-emoji">{r.emoji}</div><small>{r.milestone} WÖRTER</small><h3>{r.title}</h3>{r.description&&<p>{r.description}</p>}<Stars n={r.unlocked?3:0}/>{r.unlocked&&<div className={'reward-status '+(r.redeemed?'redeemed':'')}>{r.redeemed?'✓ Eingelöst':'Bereit zum Einlösen'}</div>}</div>)}</div></main><Bottom active="rewards" onHome={onHome} onAchievements={onAchievements}/></>}

function Achievements({items,onHome,onRewards}){const unlocked=items.filter(item=>item.unlocked).length;return <><Header back onBack={onHome}/><main className="achievements"><section className="achievement-hero"><div className="achievement-cup">⭐</div><div><div className="eyebrow">DEINE ERFOLGE</div><h1>Schau, was du schon geschafft hast!</h1><p>Jede Übung bringt dich einem neuen Abzeichen näher.</p></div></section><div className="achievement-summary"><div><b>{unlocked}</b><span>freigeschaltet</span></div><div><b>{items.length-unlocked}</b><span>noch zu entdecken</span></div><div><b>{Math.round(unlocked/items.length*100)||0}%</b><span>Sammlung komplett</span></div></div><div className="section-title"><div><h2>Deine Abzeichen</h2><p>Tippe fleißig weiter – dein Fortschritt wird automatisch gespeichert.</p></div></div><section className="achievement-grid">{items.map(item=>{const percent=Math.min(100,Math.round(item.current/item.target*100));return <article className={'achievement-card '+(item.unlocked?'unlocked':'')} key={item.id}><div className="achievement-icon">{item.unlocked?item.icon:'🔒'}</div><div className="achievement-copy"><small>{item.unlocked?'GESCHAFFT!':'NOCH IN ARBEIT'}</small><h3>{item.title}</h3><p>{item.description}</p><div className="achievement-bar"><i style={{width:`${percent}%`}}/></div><b>{Math.min(item.current,item.target)} / {item.target}</b></div></article>})}</section></main><Bottom active="achievements" onHome={onHome} onRewards={onRewards}/></>}
function ParentLogin({onClose,onSuccess}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{onSuccess(await signIn(email,password))}catch(reason){setError(reason.message)}finally{setBusy(false)}};return <div className="overlay"><form className="pin login-card" onSubmit={submit}><button type="button" className="close" onClick={onClose}><X/></button><div className="pin-icon">👩‍👧</div><h2>Eltern-Anmeldung</h2><p>Melde dich an, damit alle Familiendaten sicher deinem Konto zugeordnet werden.</p><label>E-Mail<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Passwort<input type="password" required minLength="6" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="pin-error">{error}</div>}<button className="login-submit" disabled={busy}>{busy?'Anmelden …':'Sicher anmelden'}</button></form></div>}
function Parent({onBack,onManage,onAddUnit,onRewards,onLogout,user,stats,rewardItems,analytics,units}){
 const [cloudStatus,setCloudStatus]=useState(cloudConfigured?'Bereit':'Nicht konfiguriert'),[cloudBusy,setCloudBusy]=useState(false);
 const backup=async()=>{const blob=await exportBackup();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vokabelhero-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 const restore=async e=>{if(!e.target.files[0])return;try{await importBackup(e.target.files[0]);alert('Backup wurde wiederhergestellt.');location.reload()}catch(error){alert(error.message)}};
 const cloud=async direction=>{setCloudBusy(true);setCloudStatus(direction==='up'?'Wird gesichert …':'Wird geladen …');try{const time=direction==='up'?await uploadCloudBackup():await downloadCloudBackup();setCloudStatus(`Aktuell: ${new Date(time).toLocaleString('de-DE')}`);if(direction==='down')location.reload()}catch(error){setCloudStatus(error.message)}finally{setCloudBusy(false)}};
 return <><Header back onBack={onBack}/><main className="parent-page"><div className="eyebrow">ELTERN-BEREICH</div><h1>Hallo! 👋</h1><div className="account-line"><span>Angemeldet als {user?.email}</span><button onClick={onLogout}>Abmelden</button></div><p>Deine Daten bleiben lokal verfügbar und können zusätzlich privat in Supabase gesichert werden.</p><div className="stats"><div><b>{stats.learnedWords}</b><span>Wörter gelernt</span></div><div><b>{stats.practicedUnits}</b><span>Units geübt</span></div><div><b>{stats.stars}</b><span>Sterne gesammelt</span></div></div><div className="parent-reward-note">🎁 {rewardItems.filter(r=>r.unlocked&&!r.redeemed).length} Belohnung(en) bereit zum Einlösen</div><section className="cloud-card"><div><span>☁️</span><div><b>Supabase Cloud-Backup</b><small>{cloudStatus}</small></div></div><div><button disabled={!cloudConfigured||cloudBusy} onClick={()=>cloud('up')}>Jetzt sichern</button><button disabled={!cloudConfigured||cloudBusy} onClick={()=>confirm('Lokale Daten durch die Cloud-Sicherung ersetzen?')&&cloud('down')}>Cloud laden</button></div></section><h2>Was möchtest du tun?</h2><ParentInsights analytics={analytics} units={units}/><div className="parent-grid"><button onClick={onManage}><span>🗂️</span><b>Units verwalten</b><small>Bearbeiten, sortieren, archivieren oder löschen</small><ChevronRight/></button><button onClick={onAddUnit}><span>📚</span><b>Neue Unit & Foto-Import</b><small>Vokabeln eingeben oder per Foto erkennen</small><ChevronRight/></button><button onClick={onRewards}><span>🎁</span><b>Belohnungen</b><small>Abstand und Wünsche selbst festlegen</small><ChevronRight/></button><button onClick={backup}><span>💾</span><b>Backup herunterladen</b><small>Alle Daten als JSON-Datei sichern</small><ChevronRight/></button><label className="parent-action"><span>♻️</span><b>Backup wiederherstellen</b><small>Gesicherte JSON-Datei auswählen</small><input type="file" accept="application/json" onChange={restore}/><ChevronRight/></label></div></main></>
}
function Manage({onBack,onSaved}){
 const [name,setName]=useState(`Vokabeln ${new Date().toLocaleDateString('de-DE')}`),[pairs,setPairs]=useState([['',''],['',''],['','']]),[message,setMessage]=useState(''),[columnOrder,setColumnOrder]=useState('en-de'),[removeAnnotations,setRemoveAnnotations]=useState(true);
 const update=(index,column,value)=>setPairs(current=>current.map((pair,pairIndex)=>pairIndex===index?pair.map((item,itemIndex)=>itemIndex===column?value:item):pair));
 const acceptPairs=found=>setPairs(found.length?found:[['',''],['',''],['','']]);
 const save=async()=>{const clean=pairs.filter(pair=>pair[0].trim()&&pair[1].trim());if(clean.length<3){setMessage('Bitte mindestens 3 vollständige Wortpaare eingeben.');return}const entries=clean.map(pair=>normalizeVocabularyPair(pair,removeAnnotations));const now=new Date().toISOString();const newUnit={id:crypto.randomUUID(),name:name.trim(),icon:'📘',accent:'#7248e8',soft:'#f2edff',done:0,words:entries.length,stars:[0,0,0,0,0,0,0],pairs:entries.map(entry=>[entry.de,entry.en]),entries,createdAt:now,updatedAt:now,lastPracticedAt:null};await put('units',newUnit);setMessage('Als neue Unit für heute gespeichert! Sie bleibt später zum Wiederholen erhalten. ✅');onSaved(newUnit)};
 return <><Header back onBack={onBack}/><main className="manage-page"><div className="eyebrow">NEUE TAGES-UNIT</div><h1>Heutige Vokabeln hinzufügen</h1><p>Importiere mehrere Fotos, iPhone-HEIC-Dateien oder PDF-Seiten. Vor der Erkennung kannst du jedes Bild drehen und auf den wichtigen Bereich zuschneiden.</p><label className="column-order">So stehen die Spalten im Dokument<select value={columnOrder} onChange={event=>setColumnOrder(event.target.value)}><option value="en-de">🇬🇧 Englisch links · 🇩🇪 Deutsch rechts</option><option value="de-en">🇩🇪 Deutsch links · 🇬🇧 Englisch rechts</option></select></label><OcrWorkspace columnOrder={columnOrder} onPairs={acceptPairs} onMessage={setMessage}/>{message&&<div className="import-message">{message}</div>}<label className="annotation-option"><input type="checkbox" checked={removeAnnotations} onChange={event=>setRemoveAnnotations(event.target.checked)}/><span><b>Wortarten und Hinweise fürs Lernspiel entfernen</b><small>„call v“ wird zu „call“. Wortart, Formen und Hinweise werden trotzdem getrennt in der Unit gespeichert.</small></span></label><label className="unit-name">Name der neuen Unit<input value={name} onChange={event=>setName(event.target.value)} maxLength="50"/></label><div className="pair-head"><b>🇩🇪 Deutsch</b><b>🇬🇧 Englisch</b></div>{pairs.map((pair,index)=>{const metadata=normalizeVocabularyPair(pair,true);return <div className="pair-with-meta" key={index}><div className="pair-row"><input value={pair[0]} onChange={event=>update(index,0,event.target.value)} placeholder="z. B. nennen; rufen"/><input value={pair[1]} onChange={event=>update(index,1,event.target.value)} placeholder="z. B. call v"/><button onClick={()=>pairs.length>3&&setPairs(pairs.filter((_,pairIndex)=>pairIndex!==index))}>×</button></div>{(metadata.partOfSpeech||metadata.forms.length||metadata.notes)&&<small>Gespeicherte Zusatzangaben: {metadata.partOfSpeech&&`Wortart ${metadata.partOfSpeech}`}{metadata.forms.length?` · Formen ${metadata.forms.join(', ')}`:''}{metadata.notes?` · Hinweis ${metadata.notes}`:''}</small>}</div>})}<button className="add-row" disabled={pairs.length>=30} onClick={()=>setPairs([...pairs,['','']])}>+ Weitere Zeile</button><button className="save-unit" onClick={save}>Neue Tages-Unit speichern <Check/></button></main></>;
}
function RewardAdmin({items,initialInterval,onBack,onSaved}){const [interval,setInterval]=useState(initialInterval||50);const [drafts,setDrafts]=useState(items.map(r=>({...r})));const [message,setMessage]=useState('');const emojis=['🎮','🍦','🍕','🎬','📖','🎨','⚽','🎡','🎁','⭐'];const update=(index,key,value)=>setDrafts(current=>current.map((reward,i)=>i===index?{...reward,[key]:value}:reward));const add=()=>drafts.length<10&&setDrafts([...drafts,{id:crypto.randomUUID(),emoji:'🎁',title:'Neue Belohnung',description:'',unlocked:false,redeemed:false}]);const save=async()=>{const every=Math.max(5,Math.min(500,Number(interval)||50));const prepared=drafts.filter(r=>r.title.trim()).map((r,index)=>({...r,milestone:(index+1)*every}));if(!prepared.length){setMessage('Bitte mindestens eine Belohnung anlegen.');return}await Promise.all([replaceAll('rewards',prepared),put('settings',{id:'reward-config',interval:every,updatedAt:new Date().toISOString()})]);setMessage('Belohnungsplan gespeichert! ✅');onSaved(prepared,every)};return <><Header back onBack={onBack}/><main className="reward-admin"><div className="eyebrow">ELTERN-BEREICH</div><h1>Belohnungen planen 🎁</h1><p>Lege fest, wie oft es eine Belohnung gibt und worauf sich dein Kind freuen darf.</p><label className="interval-card"><span>Belohnung alle</span><div><input type="number" min="5" max="500" step="5" value={interval} onChange={e=>setInterval(e.target.value)}/><b>richtig gelernte Wörter</b></div><small>Die Meilensteine werden automatisch berechnet.</small></label><div className="reward-editor-head"><h2>Belohnungsplan</h2><span>{drafts.length} von 10</span></div><div className="reward-editor-list">{drafts.map((reward,index)=><div className="reward-editor" key={reward.id}><div className="milestone">{(index+1)*(Number(interval)||50)}<small>WÖRTER</small></div><select value={reward.emoji} onChange={e=>update(index,'emoji',e.target.value)} aria-label="Emoji auswählen">{emojis.map(emoji=><option key={emoji}>{emoji}</option>)}</select><div><input value={reward.title} maxLength="50" onChange={e=>update(index,'title',e.target.value)} placeholder="z. B. Eis essen"/><input value={reward.description||''} maxLength="100" onChange={e=>update(index,'description',e.target.value)} placeholder="Kurze Beschreibung (optional)"/>{reward.unlocked&&<button className="redeem-toggle" onClick={()=>update(index,'redeemed',!reward.redeemed)}>{reward.redeemed?'↩ Als nicht eingelöst markieren':'✓ Als eingelöst markieren'}</button>}</div><button className="delete-reward" onClick={()=>setDrafts(drafts.filter((_,i)=>i!==index))} aria-label="Belohnung löschen">×</button></div>)}</div><button className="add-reward" disabled={drafts.length>=10} onClick={add}>+ Belohnung hinzufügen</button>{message&&<div className="import-message">{message}</div>}<button className="save-rewards" onClick={save}>Belohnungsplan speichern <Check/></button></main></>}
function App(){
 const seededRewards=rewards.map(([emoji,title,milestone,unlocked],index)=>({id:`reward-${index}`,emoji,title,milestone,unlocked,redeemed:false}));
 const initialUnitList=withMissingDates(initialUnits);
 const [page,setPage]=useState('home'),[units,setUnits]=useState(initialUnitList),[rewardItems,setRewardItems]=useState(seededRewards),[achievementItems,setAchievementItems]=useState(achievementCatalog.map(item=>({...item,current:0,unlocked:false}))),[stats,setStats]=useState(summarizeLearning([],initialUnitList)),[rewardInterval,setRewardInterval]=useState(50),[unit,setUnit]=useState(initialUnits[0]),[cloudUser,setCloudUser]=useState(getCloudUser()),[login,setLogin]=useState(false),[globalSync,setGlobalSync]=useState(getCloudStatus()),[attemptItems,setAttemptItems]=useState([]),[stageResult,setStageResult]=useState(null);
 const refreshProgress=async(currentUnits,currentRewards=rewardItems)=>{const attempts=await getAll('attempts');setAttemptItems(attempts);const summary=summarizeLearning(attempts,currentUnits);const syncedRewards=syncRewards(currentRewards,summary.learnedWords);const calculated=achievementCatalog.map(item=>calculateAchievementProgress(item,{attempts,units:currentUnits,learnedWords:summary.learnedWords}));setStats(summary);setRewardItems(syncedRewards);setAchievementItems(calculated);await Promise.all([replaceAll('rewards',syncedRewards),replaceAll('achievements',calculated)])};
 useEffect(()=>{seedDatabase(initialUnitList,rewards).then(async()=>{const [savedUnits,savedRewards,settings]=await Promise.all([getAll('units'),getAll('rewards'),getAll('settings')]);const dated=savedUnits.length?withMissingDates(savedUnits):initialUnitList;const configuredRewards=(savedRewards.length?savedRewards:seededRewards).sort((a,b)=>a.milestone-b.milestone);setUnits(dated);const config=settings.find(item=>item.id==='reward-config');if(config)setRewardInterval(config.interval);await Promise.all(dated.map(item=>put('units',item)));await refreshProgress(dated,configuredRewards)}).catch(console.error)},[]);
 useEffect(()=>subscribeCloudStatus(setGlobalSync),[]);
 useEffect(()=>{if(!cloudUser)return;syncCloudData().then(async()=>{const [savedUnits,savedRewards,settings]=await Promise.all([getAll('units'),getAll('rewards'),getAll('settings')]);const dated=withMissingDates(savedUnits);setUnits(dated);setUnit(current=>dated.find(item=>item.id===current.id)||dated[0]||current);const config=settings.find(item=>item.id==='reward-config');if(config)setRewardInterval(config.interval);await refreshProgress(dated,savedRewards)}).catch(error=>console.error('Automatische Synchronisierung fehlgeschlagen:',error))},[cloudUser?.id]);
 const finishGame=(results=[],meta={})=>{const playedLevel=+page.at(-1);const {stars:earnedStars}=scoreStage(results);const nextStars=[...(unit.stars||[]),0,0,0,0,0,0,0].slice(0,7);nextStars[playedLevel]=Math.max(nextStars[playedLevel]||0,earnedStars);const practiced={...unit,done:earnedStars?Math.max(unit.done||0,playedLevel+1):(unit.done||0),stars:nextStars,lastPracticedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const nextUnits=units.map(item=>item.id===practiced.id?practiced:item);setUnit(practiced);setUnits(nextUnits);setStageResult({results,level:playedLevel,maxStreak:meta.maxStreak||0,unit:practiced});setPage('result');markCloudPending();Promise.all([put('units',practiced)]).then(()=>refreshProgress(nextUnits)).then(()=>cloudUser&&uploadCloudBackup()).catch(error=>console.error('Lernfortschritt konnte nicht gespeichert werden:',error))};
 const rewardProgress=nextRewardProgress(rewardItems,stats.learnedWords);
 const analytics=buildParentAnalytics(attemptItems,units);
 const saveRewards=async(saved,every)=>{const now=new Date().toISOString();const synced=syncRewards(saved,stats.learnedWords).map(item=>({...item,updatedAt:now}));setRewardItems(synced);setRewardInterval(every);markCloudPending();await replaceAll('rewards',synced);if(cloudUser)await uploadCloudBackup()};
 return <><SyncIndicator status={globalSync} user={cloudUser}/>{page==='home'&&<Home onUnit={u=>{setUnit(u);setPage('unit')}} onRewards={()=>setPage('rewards')} onAchievements={()=>setPage('achievements')} onParent={()=>cloudUser?setPage('parent'):setLogin(true)} units={units} stats={stats} rewardProgress={rewardProgress}/>} {page==='unit'&&<Unit unit={unit} onBack={()=>setPage('home')} onPlay={l=>setPage('game'+l)}/>} {page.startsWith('game')&&<Game unit={unit} level={+page.at(-1)} onBack={()=>setPage('unit')} onFinish={finishGame} onAttempt={attempt=>{markCloudPending();return saveAttempt(attempt).then(()=>getAll('attempts')).then(setAttemptItems).catch(error=>console.error('Antwort konnte nicht gespeichert werden:',error))}}/>} {page==='result'&&stageResult&&<StageResult unit={stageResult.unit} level={stageResult.level} levelInfo={levels[stageResult.level]} results={stageResult.results} maxStreak={stageResult.maxStreak} onUnit={()=>setPage('unit')} onRepeat={()=>setPage(`game${stageResult.level}`)} onNext={stageResult.level<6&&stageResult.unit.done>stageResult.level?()=>setPage(`game${stageResult.level+1}`):null}/>} {page==='rewards'&&<Rewards onBack={()=>setPage('home')} onHome={()=>setPage('home')} onAchievements={()=>setPage('achievements')} rewardItems={rewardItems} stats={stats} rewardProgress={rewardProgress}/>} {page==='achievements'&&<Achievements items={achievementItems} onHome={()=>setPage('home')} onRewards={()=>setPage('rewards')}/>} {page==='parent'&&<Parent onBack={()=>setPage('home')} user={cloudUser} onLogout={()=>{signOut();setCloudUser(null);setPage('home')}} onManage={()=>setPage('unitAdmin')} onAddUnit={()=>setPage('manage')} onRewards={()=>setPage('rewardAdmin')} stats={stats} rewardItems={rewardItems} analytics={analytics} units={units}/>} {page==='unitAdmin'&&<UnitAdmin units={units} onBack={()=>setPage('parent')} onAdd={()=>setPage('manage')} onSave={async saved=>{await replaceAll('units',saved);setUnits(saved);markCloudPending();if(cloudUser)await uploadCloudBackup()}}/>} {page==='manage'&&<Manage onBack={()=>setPage('parent')} onSaved={u=>{setUnits([...units,u]);setPage('home');if(cloudUser)setTimeout(()=>uploadCloudBackup().catch(console.error),0)}}/>} {page==='rewardAdmin'&&<RewardAdmin items={rewardItems} initialInterval={rewardInterval} onBack={()=>setPage('parent')} onSaved={saveRewards}/>} {login&&<ParentLogin onClose={()=>setLogin(false)} onSuccess={user=>{setCloudUser(user);setLogin(false);setPage('parent')}}/>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
