import React,{useMemo,useState} from 'react';
import {ArrowLeft,Check} from 'lucide-react';
import {AvatarView} from './AvatarView.jsx';
import {MONSTER_STEPS,advanceMonster,meaningChoices,monsterMood} from './monster.js';

export function MonsterTraining({monsters,units,avatar,childName,onBack,onProgress,onAttempt}){
 const [monsterIndex,setMonsterIndex]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[vanishing,setVanishing]=useState(false);const monster=monsters[monsterIndex];
 const step=MONSTER_STEPS[(monster?.steps||[]).length]||MONSTER_STEPS[0],choices=useMemo(()=>monster?meaningChoices(monster,units):[],[monster?.id,step.id]);
 if(!monster)return <main className="monster-empty"><AvatarView avatar={avatar}/><h1>Alle Fehler-Monster sind vertrieben!</h1><p>Stark, {childName}! Im Moment wartet kein kniffliges Wort.</p><button onClick={onBack}>Zur Startseite</button></main>;
 const check=async value=>{const text=String(value).trim(),correct=step.id==='meaning'?text===monster.de:step.id==='spelling'?text.toLocaleLowerCase()===monster.en.toLocaleLowerCase():new RegExp(`(^|[^\\p{L}])${monster.en.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^\\p{L}]|$)`,'iu').test(text);await onAttempt({unitId:monster.unitId,level:100+(monster.steps||[]).length,word:monster.en,correct,firstTry:correct,response:text,isReview:true});if(!correct){setFeedback(step.id==='sentence'?`Fast! Verwende das Wort „${monster.en}“ in deinem englischen Satz.`:'Fast! Schau dir das Wort noch einmal genau an. 💡');return}const next=advanceMonster(monster,step.id);setAnswer('');if(next.defeatedAt){setVanishing(true);setFeedback('Geschafft! Das Fehler-Monster fliegt davon! 🎉');setTimeout(async()=>{await onProgress(next);setVanishing(false);setFeedback('');setMonsterIndex(0)},1100)}else{await onProgress(next);setFeedback(`Super! Das Monster wird freundlicher – noch ${3-next.steps.length} Aufgabe${3-next.steps.length===1?'':'n'}.`)}};
 return <main className="monster-page"><header><button onClick={onBack}><ArrowLeft/> Zurück</button><b>Fehler-Monster-Training</b><span>{monsterIndex+1}/{monsters.length}</span></header><section><AvatarView avatar={avatar} mood={feedback.startsWith('Super')?'celebrate':'help'}/><div className={`error-monster stage-${monster.steps.length} ${vanishing?'vanishing':''}`}><span>{monsterMood(monster.steps.length)}</span><i>{monster.wrong}× knifflig</i></div><div className="monster-progress">{MONSTER_STEPS.map(item=><div className={monster.steps.includes(item.id)?'done':item.id===step.id?'active':''} key={item.id}><span>{monster.steps.includes(item.id)?'✓':item.icon}</span><small>{item.title}</small></div>)}</div><div className="monster-task"><small>{monster.unitName}</small><h1>{step.id==='meaning'?`Was bedeutet „${monster.en}“?`:step.id==='spelling'?`Schreibe „${monster.de}“ auf Englisch.`:`Schreibe einen kurzen englischen Satz mit „${monster.en}“.`}</h1>{step.id==='meaning'?<div className="monster-choices">{choices.map(choice=><button onClick={()=>check(choice)} key={choice}>{choice}</button>)}</div>:<div className="monster-input"><input autoFocus value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&answer.trim()&&check(answer)} placeholder={step.id==='sentence'?`My ... ${monster.en} ...`:'Englisches Wort'}/><button disabled={!answer.trim()} onClick={()=>check(answer)}><Check/> Prüfen</button></div>}{feedback&&<p className="monster-feedback">{feedback}</p>}</div></section></main>;
}
