import React,{useEffect,useMemo,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Crop,FileImage,RotateCw,Sparkles} from 'lucide-react';
import {prepareImportFiles,transformImportAsset} from './importMedia.js';
import {recognizeVocabulary} from './ocr.js';
import {recognizeVocabularyWithAI} from './aiOcr.js';

const mergePairs=(current,incoming)=>{
 const seen=new Set();return [...current,...incoming].filter(pair=>{const key=pair.map(item=>item.toLocaleLowerCase()).join('|');if(seen.has(key))return false;seen.add(key);return pair.every(Boolean)}).slice(0,30);
};

export function OcrWorkspace({columnOrder,onPairs,onMessage}){
 const [assets,setAssets]=useState([]),[selected,setSelected]=useState(0),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[provider,setProvider]=useState('auto');
 const current=assets[selected];
 const preview=useMemo(()=>current?URL.createObjectURL(current.blob):null,[current?.blob]);
 useEffect(()=>()=>preview&&URL.revokeObjectURL(preview),[preview]);
 const patchCurrent=change=>setAssets(list=>list.map((asset,index)=>index===selected?{...asset,...change}:asset));
 const pick=async event=>{const files=[...event.target.files];if(!files.length)return;setBusy(true);onMessage('Fotos und Dokumente werden vorbereitet …');try{const prepared=await prepareImportFiles(files);setAssets(previous=>[...previous,...prepared]);setSelected(assets.length);onMessage(`${prepared.length} Bild${prepared.length===1?'':'er'} vorbereitet. Wähle die gewünschten Seiten aus.`)}catch(error){onMessage(error.message)}finally{setBusy(false);event.target.value=''}};
 const recognize=async(items,useAI=false)=>{if(!items.length)return;setBusy(true);setProgress(0);let combined=[],usedFallback=false;try{for(let index=0;index<items.length;index++){onMessage(`${useAI?'KI-':'Lokale '}Erkennung ${index+1} von ${items.length} …`);const blob=await transformImportAsset(items[index]);let found;if(useAI){try{found=await recognizeVocabularyWithAI(blob,columnOrder,provider)}catch(aiError){usedFallback=true;onMessage(`${aiError.message} Lokale Erkennung läuft …`);found=await recognizeVocabulary(blob,value=>setProgress(Math.round((index+value/100)/items.length*100)),columnOrder)}}else found=await recognizeVocabulary(blob,value=>setProgress(Math.round((index+value/100)/items.length*100)),columnOrder);combined=mergePairs(combined,found)}onPairs(combined);onMessage(`${combined.length} Wortpaare aus ${items.length} Bild${items.length===1?'':'ern'} erkannt${usedFallback?' (lokaler Ersatz, weil KI nicht erreichbar)':''} – bitte prüfen.`)}catch(error){onMessage(`Erkennung fehlgeschlagen: ${error.message}`)}finally{setBusy(false);setProgress(0)}};
 const crop=(side,value)=>patchCurrent({crop:{...current.crop,[side]:Math.min(40,Math.max(0,Number(value)))}});
 return <section className="ocr-workspace"><label className="photo-upload"><FileImage/> <b>Fotos, HEIC oder PDF auswählen</b><span>Mehrere Dateien möglich · PDF-Seiten werden einzeln angezeigt</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif,.heic,.heif,application/pdf" onChange={pick}/></label>{assets.length>0&&<><div className="asset-tabs">{assets.map((asset,index)=><button className={index===selected?'active':''} onClick={()=>setSelected(index)} key={asset.id}><input type="checkbox" checked={asset.enabled} onChange={event=>{event.stopPropagation();setAssets(list=>list.map(item=>item.id===asset.id?{...item,enabled:event.target.checked}:item))}}/><span>{asset.source==='pdf'?`Seite ${asset.page}`:'Foto'}</span></button>)}</div><div className="image-editor"><div className="image-preview"><img src={preview} alt={current.label} style={{transform:`rotate(${current.rotation}deg)`}}/></div><div className="image-tools"><b>{current.label}</b><button onClick={()=>patchCurrent({rotation:(current.rotation+90)%360})}><RotateCw/> 90° drehen</button><div className="crop-title"><Crop/> Bildränder zuschneiden</div>{['top','right','bottom','left'].map(side=><label key={side}><span>{{top:'Oben',right:'Rechts',bottom:'Unten',left:'Links'}[side]}</span><input type="range" min="0" max="40" value={current.crop[side]} onChange={event=>crop(side,event.target.value)}/><small>{current.crop[side]}%</small></label>)}</div></div><div className="workspace-nav"><button disabled={selected===0} onClick={()=>setSelected(value=>value-1)}><ChevronLeft/></button><span>{selected+1} / {assets.length}</span><button disabled={selected===assets.length-1} onClick={()=>setSelected(value=>value+1)}><ChevronRight/></button></div><label className="ai-provider"><span>KI-Anbieter</span><select value={provider} onChange={event=>setProvider(event.target.value)}><option value="auto">Automatisch</option><option value="openai">OpenAI (ChatGPT)</option><option value="anthropic">Anthropic (Claude)</option></select><small>API-Keys bleiben sicher als Supabase Secret gespeichert.</small></label><div className="ocr-actions"><button disabled={busy} onClick={()=>recognize([current])}><Crop/> Diesen Ausschnitt erneut erkennen</button><button disabled={busy||!assets.some(asset=>asset.enabled)} onClick={()=>recognize(assets.filter(asset=>asset.enabled))}><Check/> Alle ausgewählten erkennen</button><button className="ai-action" disabled={busy} onClick={()=>recognize([current],true)}><Sparkles/> Ausschnitt mit KI erkennen</button></div>{busy&&<div className="ocr-progress"><i style={{width:`${progress}%`}}/><span>{progress?`${progress}%`:'Wird vorbereitet …'}</span></div>}</>}</section>;
}
