import React,{useEffect,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowUp,Archive,Check,ChevronRight,Plus,Trash2} from 'lucide-react';
import {normalizeVocabularyPair} from './ocr.js';
import {normalizeChildName} from './profile.js';

const emptyPair=()=>['',''];
const normalize=unit=>({...unit,pairs:(unit.pairs||[]).map(pair=>[...pair])});

export function UnitAdmin({units,onBack,onAdd,onSave}){
 const [drafts,setDrafts]=useState(()=>units.filter(unit=>!unit.deletedAt).map(normalize));
 const [selected,setSelected]=useState(null),[message,setMessage]=useState('');
 useEffect(()=>setDrafts(units.filter(unit=>!unit.deletedAt).map(normalize)),[units]);
 const move=(index,direction)=>{const target=index+direction;if(target<0||target>=drafts.length)return;const next=[...drafts];[next[index],next[target]]=[next[target],next[index]];setDrafts(next)};
 const updateUnit=(id,change)=>setDrafts(current=>current.map(unit=>unit.id===id?{...unit,...change}:unit));
 const updatePair=(id,index,column,value)=>setDrafts(current=>current.map(unit=>unit.id!==id?unit:{...unit,pairs:unit.pairs.map((pair,i)=>i===index?pair.map((item,c)=>c===column?value:item):pair)}));
 const removeUnit=id=>{if(!confirm('Diese Unit wirklich löschen? Sie wird auf allen Geräten entfernt.'))return;setDrafts(current=>[...current.filter(unit=>unit.id!==id),{...current.find(unit=>unit.id===id),deletedAt:new Date().toISOString()}]);setSelected(null)};
 const save=async()=>{const invalid=drafts.find(unit=>!unit.deletedAt&&(!unit.name.trim()||unit.pairs.filter(pair=>pair[0].trim()&&pair[1].trim()).length<3));if(invalid){setMessage(`„${invalid.name||'Unbenannte Unit'}“ braucht einen Namen und mindestens 3 Wortpaare.`);return}const now=new Date().toISOString();const prepared=drafts.map((unit,index)=>{const pairs=unit.pairs.filter(pair=>pair[0].trim()&&pair[1].trim()).map(pair=>pair.map(item=>item.trim()));const entries=pairs.map(pair=>{const previous=(unit.entries||[]).find(entry=>entry.en===pair[1]||entry.originalEn===pair[1]);return previous?{...previous,de:pair[0],en:pair[1]}:normalizeVocabularyPair(pair,true)});return {...unit,name:unit.name.trim(),pairs,entries,words:pairs.length,sortOrder:index,updatedAt:now}});await onSave(prepared);setMessage('Alle Unit-Änderungen wurden gespeichert und werden synchronisiert. ✓')};
 const current=drafts.find(unit=>unit.id===selected&&!unit.deletedAt);
 return <><header className="tool-header"><button onClick={onBack}><ArrowLeft/></button><b>Units verwalten</b><button className="new-unit" onClick={onAdd}><Plus/> Neue Unit</button></header><main className="unit-admin"><div className="admin-title"><div><small>ELTERN-BEREICH</small><h1>Units & Vokabeln</h1><p>Bearbeiten, archivieren, sortieren oder sicher löschen.</p></div></div><div className="unit-admin-layout"><section className="admin-unit-list">{drafts.filter(unit=>!unit.deletedAt).map((unit,index)=><article className={selected===unit.id?'selected':''} key={unit.id}><button className="unit-select" onClick={()=>setSelected(unit.id)}><span>{unit.icon||'📘'}</span><div><b>{unit.name}</b><small>{unit.words||unit.pairs.length} Wörter · {unit.archived?'Archiviert':`${unit.done||0}/7 Stufen`}</small></div><ChevronRight/></button><div className="order-actions"><button disabled={index===0} onClick={()=>move(index,-1)} aria-label="Nach oben"><ArrowUp/></button><button disabled={index===drafts.filter(u=>!u.deletedAt).length-1} onClick={()=>move(index,1)} aria-label="Nach unten"><ArrowDown/></button></div></article>)}</section>{current?<section className="unit-editor"><label>Unit-Name<input value={current.name} maxLength="60" onChange={e=>updateUnit(current.id,{name:e.target.value})}/></label><label className="archive-check"><input type="checkbox" checked={Boolean(current.archived)} onChange={e=>updateUnit(current.id,{archived:e.target.checked})}/><Archive/> Unit archivieren <small>Archivierte Units bleiben mit Fortschritt erhalten, erscheinen aber nicht beim Kind.</small></label><div className="editor-head"><b>Vokabeln</b><span>{current.pairs.length}/30</span></div>{current.pairs.map((pair,index)=><div className="edit-pair" key={index}><input aria-label={`Deutsch ${index+1}`} value={pair[0]} onChange={e=>updatePair(current.id,index,0,e.target.value)}/><input aria-label={`Englisch ${index+1}`} value={pair[1]} onChange={e=>updatePair(current.id,index,1,e.target.value)}/><button disabled={current.pairs.length<=3} onClick={()=>updateUnit(current.id,{pairs:current.pairs.filter((_,i)=>i!==index)})} aria-label="Vokabel löschen"><Trash2/></button></div>)}<button className="add-vocab" disabled={current.pairs.length>=30} onClick={()=>updateUnit(current.id,{pairs:[...current.pairs,emptyPair()]})}><Plus/> Vokabel hinzufügen</button><button className="danger-unit" onClick={()=>removeUnit(current.id)}><Trash2/> Unit löschen</button></section>:<section className="unit-editor empty"><span>👈</span><h2>Unit auswählen</h2><p>Wähle links eine Unit zum Bearbeiten aus.</p></section>}</div>{message&&<div className="admin-message">{message}</div>}<button className="save-admin" onClick={save}><Check/> Änderungen speichern</button></main></>
}

export function ChildProfileSettings({name,onSave}){
 const [draft,setDraft]=useState(name),[message,setMessage]=useState('');
 useEffect(()=>setDraft(name),[name]);
 const submit=async event=>{event.preventDefault();const normalized=normalizeChildName(draft);setDraft(normalized);await onSave(normalized);setMessage(`Gespeichert – die App begrüßt jetzt ${normalized}.`)};
 return <form className="child-profile-card" onSubmit={submit}><div className="profile-avatar">🧒</div><div><label htmlFor="child-name">Name des Kindes</label><small>Wird auf der Startseite und in motivierenden Nachrichten verwendet.</small></div><input id="child-name" value={draft} onChange={event=>{setDraft(event.target.value);setMessage('')}} maxLength="30" autoComplete="off" placeholder="Vorname"/><button type="submit" disabled={!draft.trim()}><Check/> Namen speichern</button>{message&&<p role="status">{message}</p>}</form>;
}

export function ParentInsights({analytics,units}){
 const unitNames=new Map(units.map(unit=>[unit.id,unit.name]));
 const max=Math.max(1,...analytics.lastSevenDays.map(day=>day.answers));
 return <section className="parent-insights"><div className="insight-metrics"><article><b>{analytics.firstTryRate}%</b><span>Erstversuch-Quote</span></article><article><b>{analytics.errorRate}%</b><span>Fehlerquote</span></article><article><b>{analytics.learningDays}</b><span>Lerntage</span></article><article><b>{analytics.averageRoundMinutes} min</b><span>Ø Lernrunde</span></article></div><div className="insight-grid"><article className="hard-words"><h2>Schwierigste Wörter</h2>{analytics.hardestWords.length?analytics.hardestWords.map(item=><div key={`${item.unitId}:${item.word}`}><span><b>{item.word}</b><small>{unitNames.get(item.unitId)||'Gelöschte Unit'} · {item.wrong} von {item.total} Antworten nicht richtig</small></span><strong>{item.errorRate}%</strong></div>):<p>Noch keine Fehler – stark! 🎉</p>}</article><article className="week-chart"><h2>Letzte sieben Tage</h2><div>{analytics.lastSevenDays.map(day=><span key={day.date}><i style={{height:`${Math.max(4,day.answers/max*100)}%`}} title={`${day.answers} Antworten`}/><b>{day.answers}</b><small>{day.label}</small></span>)}</div></article></div><article className="error-types"><h2>Fehlertypen & Hilfen</h2><p>Verwendete Hinweise: <b>{analytics.hintsUsed||0}</b></p><div>{Object.entries(analytics.errorTypes||{}).sort((a,b)=>b[1]-a[1]).map(([type,count])=><span key={type}><b>{({translation:'Übersetzung verwechselt',missing:'Buchstabe fehlt',extra:'Buchstabe zu viel',transposed:'Buchstaben vertauscht',capitalization:'Groß-/Kleinschreibung',punctuation:'Apostroph oder Zeichen',phonetic:'Nach Gehör geschrieben',spelling:'Schreibweise',unknown:'Sonstiger Fehler'})[type]||type}</b><strong>{count}×</strong></span>)}</div>{!Object.keys(analytics.errorTypes||{}).length&&<p>Noch keine Fehlermuster erkannt.</p>}</article><article className="unit-progress-admin"><h2>Fortschritt pro Unit</h2>{analytics.unitProgress.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.archived?'Archiviert':item.lastPracticedAt?`Zuletzt ${new Date(item.lastPracticedAt).toLocaleDateString('de-DE')}`:'Noch nicht begonnen'}</small></span><div><i style={{width:`${item.percent}%`}}/></div><strong>{item.done}/7</strong></div>)}</article>{analytics.lastLearnedAt&&<p className="last-learned">Zuletzt gelernt: <b>{new Date(analytics.lastLearnedAt).toLocaleString('de-DE')}</b> · {analytics.totalAnswers} Antworten insgesamt</p>}</section>
}
