import React,{useMemo,useState} from 'react';
import {ArrowLeft,Check,Volume2,Zap} from 'lucide-react';
import {battleModeLabel,battlePicture,buildBattleRounds,scrambleWord,settleBattleRound} from './battle.js';

export function VocabularyBattle({units,childName,onBack,onComplete}){
 const rounds=useMemo(()=>buildBattleRounds(units),[units]),[index,setIndex]=useState(0),[scores,setScores]=useState({child:0,opponent:0}),[answer,setAnswer]=useState(''),[result,setResult]=useState(null),[finished,setFinished]=useState(false);
 const round=rounds[index],scrambled=useMemo(()=>round?scrambleWord(round.en):'',[round?.id,index]);
 if(!rounds.length)return <main className="battle-empty"><h1>Noch keine Battle-Vokabeln</h1><p>Lege zuerst eine Unit mit Vokabeln an.</p><button onClick={onBack}>Zurück</button></main>;
 const speak=()=>{if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined')return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(round.en);utterance.lang='en-GB';utterance.rate=.78;window.speechSynthesis.speak(utterance)};
 const choose=value=>{if(result)return;const correct=value.trim().toLocaleLowerCase()===round.answer.toLocaleLowerCase(),outcome=settleBattleRound(round,correct),next={child:scores.child+outcome.childPoints,opponent:scores.opponent+outcome.opponentPoints};setAnswer(value);setScores(next);setResult({...outcome,correct});};
 const next=()=>{if(index===rounds.length-1){setFinished(true);onComplete?.({...scores,total:rounds.length,completedAt:new Date().toISOString()});return}setIndex(value=>value+1);setAnswer('');setResult(null)};
 if(finished)return <main className="battle-finish"><div className="battle-crown">👑</div><div className="eyebrow">BATTLE BEENDET</div><h1>{scores.child>scores.opponent?`${childName} gewinnt!`:'Das war richtig knapp!'}</h1><div className="battle-final-score"><b>{scores.child}</b><span>:</span><b>{scores.opponent}</b></div><p>{scores.child>scores.opponent?'Du hast den Vokabel-Bot besiegt. Stark gespielt! 🎉':'Beim nächsten Battle schnappst du dir die Krone! 💪'}</p><button onClick={onBack}>Zurück zur Startseite</button></main>;
 const prompt=round.mode==='translation'?<>Was heißt <b>„{round.de}“</b> auf Englisch?</>:round.mode==='hearing'?<>Höre genau hin und wähle die deutsche Bedeutung.</>:round.mode==='picture'?<><span className="battle-picture" role="img" aria-label={`Bildhinweis für ${round.de}`}>{battlePicture(round.en,round.icon)}</span> Welches englische Wort passt zu diesem Bild?</>:round.mode==='scramble'?<>Ordne den Buchstabensalat: <b className="scramble">{scrambled}</b></>:<>Vervollständige den Satz: „Für <b>{round.de}</b> brauche ich das englische Wort …“</>;
 return <main className={`battle-page mode-${round.mode}`}><header className="battle-header"><button onClick={onBack}><ArrowLeft/> Beenden</button><div><Zap/> Vokabel-Battle</div><span>Runde {index+1}/10</span></header><section className="battle-arena"><div className="battle-score"><div><span>🧒</span><b>{childName}</b><strong>{scores.child}</strong></div><i>VS</i><div><span>🤖</span><b>Vokabel-Bot</b><strong>{scores.opponent}</strong></div></div><div className="battle-mode">{battleModeLabel(round.mode)}</div><h1>{prompt}</h1>{round.mode==='hearing'&&<button className="listen-battle" onClick={speak}><Volume2/> Wort anhören</button>}<div className="battle-choices">{round.choices.map(choice=><button key={choice} disabled={Boolean(result)} className={result&&choice===round.answer?'correct':result&&choice===answer?'wrong':''} onClick={()=>choose(choice)}>{choice}</button>)}</div>{result&&<div className={`battle-feedback ${result.winner}`}><b>{result.correct?'Richtig!':'Fast!'}</b><span>{result.message}</span><button onClick={next}>{index===9?'Ergebnis ansehen':'Nächstes Duell'} <Check/></button></div>}<p className="battle-origin">Aus den letzten Units · {round.unitName}</p></section></main>;
}
