import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ChevronRight,Clock,Flag,Heart} from 'lucide-react';
import {AvatarView} from './AvatarView.jsx';
import {buildRunnerCourse,runnerStars} from './runner.js';

const ROUND_SECONDS=8;
export function WordRunner({units,avatar,childName,onBack,onComplete}){
 const course=useMemo(()=>buildRunnerCourse(units),[units]),[index,setIndex]=useState(0),[seconds,setSeconds]=useState(ROUND_SECONDS),[score,setScore]=useState(0),[answer,setAnswer]=useState(''),[status,setStatus]=useState('running'),[finished,setFinished]=useState(false),startedAt=useRef(Date.now()),locked=useRef(false);const item=course[index];
 const choose=value=>{if(locked.current||!item)return;locked.current=true;const correct=value===item.answer;setAnswer(value);setStatus(correct?'correct':'wrong');if(correct)setScore(value=>value+1)};
 useEffect(()=>{if(!item||finished||status!=='running')return;setSeconds(ROUND_SECONDS);locked.current=false;const timer=setInterval(()=>setSeconds(value=>{if(value<=1){clearInterval(timer);locked.current=true;setStatus('timeout');return 0}return value-1}),1000);return()=>clearInterval(timer)},[index,finished,status==='running']);
 const next=()=>{if(index>=course.length-1){const finalScore=score+(status==='correct'?0:0);setFinished(true);onComplete?.({correct:finalScore,total:course.length,stars:runnerStars(finalScore,course.length),durationMs:Date.now()-startedAt.current});return}setIndex(value=>value+1);setAnswer('');setStatus('running')};
 if(!course.length)return <main className="runner-empty"><h1>Noch keine Strecke verfügbar</h1><p>Lege zuerst mindestens eine Unit mit Vokabeln an.</p><button onClick={onBack}>Zurück</button></main>;
 if(finished){const stars=runnerStars(score,course.length);return <main className="runner-finish"><AvatarView avatar={avatar} mood="celebrate"/><Flag/><div className="eyebrow">ZIEL ERREICHT</div><h1>Starker Lauf, {childName}!</h1><div className="runner-stars">{'⭐'.repeat(stars)}{'☆'.repeat(3-stars)}</div><b>{score} von {course.length} Kreuzungen geschafft</b><p>{stars>=2?'Du hast blitzschnell die richtigen Wege gefunden!':'Jeder Lauf macht dich sicherer. Versuch die Strecke gleich noch einmal!'}</p><button onClick={onBack}>Zur Startseite</button></main>}
 return <main className={`runner-page ${status}`}><header><button onClick={onBack}><ArrowLeft/> Beenden</button><b>Word Runner</b><span>{index+1}/{course.length}</span></header><section className="runner-world"><div className="runner-hud"><span><Heart fill="#f25d76"/> {score}</span><span className={seconds<=3?'urgent':''}><Clock/> {seconds}s</span></div><div className="runner-track"><div className="runner-scenery">☁️　🌳　　　　🏠　　☁️</div><div className="runner-avatar"><AvatarView avatar={avatar} size="small" mood={status==='correct'?'celebrate':status==='running'?'ready':'help'}/></div><div className="runner-road"><i/><i/><i/></div></div><div className="runner-crossroad"><small>{item.direction==='de-en'?'DEUTSCH → ENGLISCH':'ENGLISCH → DEUTSCH'} · {item.unitName}</small><h1>Welcher Weg passt zu „<em>{item.prompt}</em>“?</h1><div className="runner-paths">{item.choices.map((choice,choiceIndex)=><button key={choice} disabled={status!=='running'} onClick={()=>choose(choice)} className={status!=='running'?(choice===item.answer?'right':choice===answer?'wrong':''):''}><span>{['←','↑','→'][choiceIndex]}</span><b>{choice}</b></button>)}</div>{status!=='running'&&<div className={`runner-feedback ${status}`}>{status==='correct'?<>⚡ Super! Der Weg ist frei.</>:status==='timeout'?<>💡 Die Zeit war knapp. Richtig wäre <b>{item.answer}</b>.</>:<>Fast! Der richtige Weg war <b>{item.answer}</b>.</>}<button onClick={next}>{index===course.length-1?'Zum Ergebnis':'Weiterlaufen'} <ChevronRight/></button></div>}</div></section></main>;
}
